export const legacyRedirects: Record<string, string> = {
  '/city/salalh': '/countries/oman-cities/salalah',
  '/city/london': '/countries/uk-cities/london',
  '/locations/satyanarayan-katha-in-bradford-book-online-or-at-home-in-bradford': '/countries/uk-cities/bradford/satyanarayan-katha-in-bradford-book-online-or-at-home-in-bradford',
  '/city/mumbai': '/countries/india-cities/mumbai',
  '/locations/satyanarayan-puja-in-sheffield': '/countries/uk-cities/sheffield/satyanarayan-puja-in-sheffield',
  '/pujas/ganesh-puja-muscat': '/countries/oman-cities/muscat/ganesh-puja-in-muscat-muscat-governorate',
  '/city/abudhabi': '/countries/uae-cities/abudhabi',
  '/city/ajman': '/countries/uae-cities/ajman',
  '/city/birmingham': '/countries/uk-cities/birmingham',
  '/city/bradford': '/countries/uk-cities/bradford',
  '/city/cardiff': '/countries/uk-cities/cardiff',
  '/city/coventry': '/countries/uk-cities/coventry',
  '/city/dallas': '/countries/united-states-cities/dallas',
  '/city/delhi': '/countries/india-cities/delhi',
  '/city/dubai': '/countries/uae-cities/dubai',
  '/city/edinburgh': '/countries/uk-cities/edinburgh',
  '/city/frisco': '/countries/united-states-cities/Frisco',
  '/city/fujairah': '/countries/uae-cities/Fujairah',
  '/city/glasgow': '/countries/uk-cities/Glasgow',
  '/city/houston': '/countries/united-states-cities/houston',
  '/city/irving': '/countries/united-states-cities/Irving',
  '/city/jersey-city': '/countries/united-states-cities/jersey-city',
  '/city/leeds': '/countries/uk-cities/leeds',
  '/city/leicester': '/countries/uk-cities/Leicester',
  '/city/manchester': '/countries/uk-cities/Manchester',
  '/city/muscat': '/countries/oman-cities/muscat',
  '/city/newcastle': '/countries/uk-cities/newcastle',
  '/city/newyork': '/countries/united-states-cities/newyork',
  '/city/nottingham': '/countries/uk-cities/nottingham',
  '/city/plano': '/countries/united-states-cities/Plano',
  '/city/preston': '/countries/uk-cities/preston',
  '/city/rasalkhaimah': '/countries/uae-cities/rasalkhaimah',
  '/city/san-jose': '/countries/united-states-cities/san-jose',
  '/city/sharjah': '/countries/uae-cities/sharjah',
  '/city/sheffield': '/countries/uk-cities/sheffield',
  '/city/sohar': '/countries/oman-cities/sohar',
  '/city/southampton': '/countries/uk-cities/southampton',
  '/city/sur': '/countries/oman-cities/sur',
  '/city/swindon': '/countries/uk-cities/swindon',
  '/city/toronto': '/countries/canada-cities/toronto',
  '/city/ummalquwain': '/countries/uae-cities/ummalquwain',
  '/city/varanasi': '/countries/india-cities/varanasi',
  '/city/wolverhampton': '/countries/uk-cities/wolverhampton',
  '/countries/india/cities': '/countries/india-cities',
  '/countries/oman-cities/salalh/ganesh-puja-book-a-pandit-for-your-home-in-salalah-dhofar': '/countries/oman-cities/salalh/ganesh-puja-in-salalah-dhofar',
  '/countries/oman/cities': '/countries/oman-cities',
  '/countries/uae-cities/fujairah': '/countries/uae-cities/Fujairah',
  '/countries/uae-cities/fujairah/ganesh-puja-in-fujairah-emirate': '/countries/uae-cities/Fujairah/ganesh-puja-in-fujairah-emirate',
  '/countries/uae/cities': '/countries/uae-cities',
  '/countries/uk-cities/cardiff/satyanarayan-puja-book-online-or-at-home-with-naman-puja-in-cardiff': '/countries/uk-cities/cardiff',
  '/countries/uk/cities': '/countries/uk-cities',
  '/countries/united-states-cities/Irving/ganesh-puja-in-irving-in-irving-texas': '/countries/united-states-cities/Irving/ganesh-puja-in-irving-texas',
  '/locations/ganesh-puja-in-dallas-in-dallas-texas': '/countries/united-states-cities/dallas/ganesh-puja-in-dallas-in-dallas-texas',
  '/locations/ganesh-puja-in-dallas-texas': '/countries/united-states-cities/dallas/ganesh-puja-in-dallas-in-dallas-texas',
  '/locations/ganesh-puja-in-frisco-in-frisco-texas': '/countries/united-states-cities/Frisco/ganesh-puja-in-frisco-in-frisco-texas',
  '/locations/ganesh-puja-in-houston': '/countries/united-states-cities/houston/ganesh-puja-in-houston',
  '/locations/ganesh-puja-in-irving-in-irving-texas': '/countries/united-states-cities/Irving/ganesh-puja-in-irving-texas',
  '/locations/ganesh-puja-in-jersey-city-in-jersey-city-new-jersey': '/countries/united-states-cities/jersey-city/ganesh-puja-in-jersey-city-in-jersey-city-new-jersey',
  '/locations/ganesh-puja-in-muscat-muscat-governorate': '/countries/oman-cities/muscat/ganesh-puja-in-muscat-muscat-governorate',
  '/locations/ganesh-puja-in-plano-texas': '/countries/united-states-cities/Plano/ganesh-puja-in-plano-texas',
  '/locations/ganesh-puja-in-salalah-dhofar': '/countries/oman-cities/salalh/ganesh-puja-in-salalah-dhofar',
  '/locations/ganesh-puja-in-sohar-al-batinah-north': '/countries/oman-cities/sohar/ganesh-puja-in-sohar-al-batinah-north',
  '/locations/ganesh-puja-in-sur-ash-sharqiyah-south': '/countries/oman-cities/sur/ganesh-puja-in-sur-ash-sharqiyah-south',
  '/locations/rudrabhishek-puja-in-san-jose-california': '/countries/united-states-cities/san-jose/rudrabhishek-puja-in-san-jose-california',
  '/locations/rudrabhisheka-puja-in-san-jose-california': '/countries/united-states-cities/san-jose/rudrabhishek-puja-in-san-jose-california',
  '/locations/san-jose-in-san-jose-california': '/countries/united-states-cities/san-jose/rudrabhishek-puja-in-san-jose-california',
  '/locations/satyanarayan-katha-book-a-pandit-online-or-at-home-in-leeds': '/countries/uk-cities/leeds/satyanarayan-katha-book-a-pandit-online-or-at-home-in-leeds',
  '/locations/satyanarayan-katha-book-online-today-in-leeds': '/countries/uk-cities/leeds/satyanarayan-katha-book-a-pandit-online-or-at-home-in-leeds',
  '/locations/satyanarayan-katha-in-birmingham-or-online-and-at-home-booking-in-birmingham-west-midlands': '/countries/uk-cities/birmingham/satyanarayan-katha-in-birmingham-west-midlands',
  '/locations/satyanarayan-katha-in-birmingham-west-midlands': '/countries/uk-cities/birmingham/satyanarayan-katha-in-birmingham-west-midlands',
  '/locations/satyanarayan-katha-in-edinburgh-in-edinburgh-scotland': '/countries/uk-cities/edinburgh/satyanarayan-katha-in-edinburgh-in-edinburgh-scotland',
  '/locations/satyanarayan-katha-in-leicester-leicestershire': '/countries/uk-cities/Leicester/satyanarayan-katha-in-leicester-leicestershire',
  '/locations/satyanarayan-katha-in-newcastle-north-east-england': '/countries/uk-cities/newcastle/satyanarayan-katha-in-newcastle-north-east-england',
  '/locations/satyanarayan-katha-in-wolverhampton-book-online-today-in-wolverhampton-west-midlands': '/countries/uk-cities/wolverhampton/satyanarayan-katha-in-wolverhampton-book-online-today-in-wolverhampton-west-midlands',
  '/locations/satyanarayan-puja-book-online-or-at-home-with-naman-puja-in-cardiff': '/countries/uk-cities/cardiff',
  '/locations/satyanarayan-puja-in-abu-dhabi-abu-dhabi': '/countries/uae-cities/abudhabi/satyanarayan-puja-in-abu-dhabi-abu-dhabi',
  '/locations/satyanarayan-puja-in-coventry-book-online-or-at-home-with-naman-puja-in-coventry': '/countries/uk-cities/coventry/satyanarayan-puja-in-coventry-book-online-or-at-home-with-naman-puja-in-coventry',
  '/locations/satyanarayan-puja-in-delhi': '/countries/india-cities/delhi/satyanarayan-puja-in-delhi',
  '/locations/satyanarayan-puja-in-dubai-book-a-verified-pandit-for-home-or-temple-worship-in-dubai-emirate': '/countries/uae-cities/dubai/satyanarayan-puja-in-dubai-book-a-verified-pandit-for-home-or-temple-worship-in-dubai-emirate',
  '/locations/satyanarayan-puja-in-manchester-greater-manchester': '/countries/uk-cities/Manchester/satyanarayan-puja-in-manchester-greater-manchester',
  '/locations/satyanarayan-puja-in-muscat-sultanate-of-muscat': '/countries/oman-cities/muscat/satyanarayan-puja-in-muscat-sultanate-of-muscat',
  '/locations/satyanarayan-puja-in-nottingham-book-a-pandit-for-home-or-online-katha-in-nottingham-east-midlands-england': '/countries/uk-cities/nottingham/satyanarayan-puja-in-nottingham-east-midlands-england',
  '/locations/satyanarayan-puja-in-nottingham-east-midlands-england': '/countries/uk-cities/nottingham/satyanarayan-puja-in-nottingham-east-midlands-england',
  '/locations/satyanarayan-puja-in-preston-lancashire': '/countries/uk-cities/preston/satyanarayan-puja-in-preston-lancashire',
  '/locations/satyanarayan-puja-in-salalah-dhofar': '/countries/oman-cities/salalh/satyanarayan-puja-in-salalah-dhofar',
  '/locations/satyanarayan-puja-in-salalah-oman-or-naman-pooja-in-salalah-dhofar': '/countries/oman-cities/salalh/satyanarayan-puja-in-salalah-dhofar',
  '/locations/satyanarayan-puja-in-sharjah-book-a-pandit-for-your-home-in-sharjah-sharjah': '/countries/uae-cities/sharjah/satyanarayan-puja-in-sharjah-book-a-pandit-for-your-home-in-sharjah-sharjah',
  '/locations/satyanarayan-puja-in-southampton': '/countries/uk-cities/southampton/satyanarayan-puja-in-southampton',
  '/locations/satyanarayan-puja-in-swindon-book-online-or-at-home-with-naman-puja-in-swindon-south-west-england': '/countries/uk-cities/swindon/satyanarayan-puja-in-swindon-south-west-england',
  '/locations/satyanarayan-puja-online-and-at-home-puja-booking-in-london-capital-city': '/countries/uk-cities/london/satyanarayan-puja-online-and-at-home-puja-booking-in-london-capital-city',
  '/pujas/ajman': '/countries/uae-cities/ajman/ganesh-puja-in-ajman-ajman',
  '/pujas/annaprasan-puja': '/pujas/pitrudosh-puja',
  '/pujas/annaprashan-puja-muscat': '/countries/oman-cities/muscat/annaprashan-puja-muscat-in-muscat-muscat-governorate',
  '/pujas/boston': '/countries/united-states-cities/boston/ganesh-puja-book-online-or-at-home-naman-puja-in-boston',
  '/pujas/brandford': '/countries/uk-cities/bradford',
  '/pujas/cardiff': '/countries/uk-cities/cardiff',
  '/pujas/dubai': '/countries/uae-cities/dubai/satyanarayan-puja-in-dubai-book-a-verified-pandit-for-home-or-temple-worship-in-dubai-emirate',
  '/pujas/edison-nj': '/countries/united-states-cities/edison-nj/ganesh-puja-in-edison-nj-in-edison-new-jersey',
  '/pujas/frisco': '/countries/united-states-cities/Frisco/ganesh-puja-in-frisco-in-frisco-texas',
  '/pujas/fujairah': '/countries/uae-cities/Fujairah/ganesh-puja-in-fujairah-emirate',
  '/pujas/ganesh-puja-abu-dhabi': '/countries/uae-cities/abudhabi/ganesh-puja-in-abu-dhabi-in-abu-dhabi-abu-dhabi',
  '/pujas/ganesh-puja-atlanta': '/countries/united-states-cities/atlanta/ganesh-puja-in-atlanta-georgia-usa',
  '/pujas/ganesh-puja-bellevue': '/countries/united-states-cities/bellevue/ganesh-puja-in-bellevue-washington',
  '/pujas/ganesh-puja-chicago': '/countries/united-states-cities/ganesh-puja-chicago/ganesh-puja-in-chicago-in-chicago-illinois',
  '/pujas/ganesh-puja-dallas': '/countries/united-states-cities/dallas/ganesh-puja-in-dallas-in-dallas-texas',
  '/pujas/ganesh-puja-fremont': '/countries/united-states-cities/fremont/ganesh-puja-in-fremont-california',
  '/pujas/ganesh-puja-irving': '/countries/united-states-cities/Irving/ganesh-puja-in-irving-texas',
  '/pujas/ganesh-puja-jersey-city': '/countries/united-states-cities/jersey-city/ganesh-puja-in-jersey-city-in-jersey-city-new-jersey',
  '/pujas/ganesh-puja-london': '/countries/uk-cities/london/ganesh-puja-in-london-capital-city',
  '/pujas/ganesh-puja-online-booking': '/countries/united-states-cities/ganesh-puja-chicago/ganesh-puja-in-chicago-in-chicago-illinois',
  '/pujas/ganesh-puja-salalah': '/countries/oman-cities/salalh/ganesh-puja-in-salalah-dhofar',
  '/pujas/ganesh-puja-san-francisco': '/countries/united-states-cities/san-francisco/ganesh-puja-in-san-francisco-california-usa',
  '/pujas/ganesh-puja-san-jose': '/countries/united-states-cities/san-jose/ganesh-puja-in-san-jose-california',
  '/pujas/ganesh-puja-sharjah': '/countries/uae-cities/sharjah/ganesh-puja-in-sharjah-in-sharjah-sharjah',
  '/pujas/ganesh-puja-sohar': '/countries/oman-cities/sohar/ganesh-puja-in-sohar-al-batinah-north',
  '/pujas/ganesh-puja-sur': '/countries/oman-cities/sur/ganesh-puja-in-sur-ash-sharqiyah-south',
  '/pujas/ganesh-puja-washington-dc-metro': '/countries/united-states-cities/ganesh-puja-washington-dc-metro/ganesh-puja-in-the-washington-dc-metro-area-in-washington-dc-metro-area-district-of-columbia',
  '/pujas/glasgow': '/countries/uk-cities/Glasgow/satyanarayan-katha-in-glasgow-scotland',
  '/pujas/houston': '/countries/united-states-cities/houston/ganesh-puja-in-houston',
  '/pujas/leeds': '/countries/uk-cities/leeds/satyanarayan-katha-book-a-pandit-online-or-at-home-in-leeds',
  '/pujas/london': '/countries/uk-cities/london/ganesh-puja-in-london-capital-city',
  '/pujas/losangeles': '/countries/united-states-cities/losangeles',
  '/pujas/manchester': '/countries/uk-cities/Manchester/satyanarayan-puja-in-manchester-greater-manchester',
  '/pujas/morrisville': '/countries/united-states-cities/morrisville/ganesh-puja-naman-puja-online-and-at-home-in-morrisville',
  '/pujas/muscat': '/countries/oman-cities/muscat/ganesh-puja-in-muscat-muscat-governorate',
  '/pujas/newwyork': '/countries/united-states-cities/newyork',
  '/pujas/philadelphia': '/countries/united-states-cities/Philadelphia/ganesh-puja-in-philadelphia-pennsylvania',
  '/pujas/pitrudosh-puja-online-booking': '/pujas/pitrudosh-puja',
  '/pujas/plano': '/countries/united-states-cities/Plano/ganesh-puja-in-plano-texas',
  '/pujas/poojas-in-oman-annaprashan-puja-salalah': '/countries/oman-cities/salalh/annaprashan-puja-salalah-in-salalah-dhofar',
  '/pujas/poojas-in-oman-annaprashan-puja-sohar': '/countries/oman-cities/sohar/ganesh-puja-in-sohar-al-batinah-north',
  '/pujas/rasaikhaimah': '/countries/uae-cities/rasalkhaimah',
  '/pujas/redmond': '/countries/united-states-cities/redmond/ganesh-puja-online-and-at-home-or-naman-puja-in-redmond',
  '/pujas/rudrabhishek-puja-dubai': '/countries/uae-cities/dubai/rudrabhishek-puja-in-dubai-uae-in-dubai-emirate',
  '/pujas/rudrabhishek-puja-muscat': '/countries/oman-cities/muscat/rudrabhishek-puja-in-muscat-kamini-in-muscat-muscat-governorate',
  '/pujas/rudrabhishek-puja-salalah': '/countries/oman-cities/salalh/ganesh-puja-in-salalah-dhofar',
  '/pujas/rudrabhishek-puja-san-jose': '/countries/united-states-cities/san-jose/rudrabhishek-puja-in-san-jose-california',
  '/pujas/salah': '/countries/oman-cities/salalh',
  '/pujas/satyanarayan': '/pujas/satyanarayan-katha',
  '/pujas/satyanarayan-katha-birmingham': '/countries/uk-cities/birmingham/satyanarayan-katha-in-birmingham-west-midlands',
  '/pujas/satyanarayan-katha-edinburgh': '/countries/uk-cities/edinburgh/satyanarayan-katha-in-edinburgh-in-edinburgh-scotland',
  '/pujas/satyanarayan-katha-leicester': '/countries/uk-cities/Leicester/satyanarayan-katha-in-leicester-leicestershire',
  '/pujas/satyanarayan-katha-wolverhampton': '/countries/uk-cities/wolverhampton/satyanarayan-katha-in-wolverhampton-book-online-today-in-wolverhampton-west-midlands',
  '/pujas/satyanarayan-puja-abu-dhabi': '/countries/uae-cities/abudhabi/satyanarayan-puja-in-abu-dhabi-abu-dhabi',
  '/pujas/satyanarayan-puja-coventry': '/countries/uk-cities/coventry/satyanarayan-puja-in-coventry-book-online-or-at-home-with-naman-puja-in-coventry',
  '/pujas/satyanarayan-puja-dubai': '/countries/uae-cities/dubai/satyanarayan-puja-in-dubai-book-a-verified-pandit-for-home-or-temple-worship-in-dubai-emirate',
  '/pujas/satyanarayan-puja-muscat': '/countries/oman-cities/muscat/satyanarayan-puja-in-muscat-sultanate-of-muscat',
  '/pujas/satyanarayan-puja-newcastle': '/countries/uk-cities/newcastle/satyanarayan-katha-in-newcastle-north-east-england',
  '/pujas/satyanarayan-puja-nottingham': '/countries/uk-cities/nottingham/satyanarayan-puja-in-nottingham-east-midlands-england',
  '/pujas/satyanarayan-puja-preston': '/countries/uk-cities/preston/satyanarayan-puja-in-preston-lancashire',
  '/pujas/satyanarayan-puja-sharjah': '/countries/uae-cities/sharjah/satyanarayan-puja-in-sharjah-book-a-pandit-for-your-home-in-sharjah-sharjah',
  '/pujas/satyanarayan-puja-swindon': '/countries/uk-cities/swindon/satyanarayan-puja-in-swindon-south-west-england',
  '/pujas/seattle': '/countries/united-states-cities/seattle/ganesh-puja-in-seattle-in-seattle-washington',
  '/pujas/sheffield': '/countries/uk-cities/sheffield/satyanarayan-puja-in-sheffield',
  '/pujas/southampton': '/countries/uk-cities/southampton/satyanarayan-puja-in-southampton',
  '/pujas/sunnyvale': '/countries/united-states-cities/sunnyvale/ganesh-puja-naman-puja-online-and-at-home-in-sunnyvale',
  '/pujas/umm-al-quwain': '/countries/uae-cities/ummalquwain/ganesh-puja-in-umm-al-quwain-umm-al-quwain',
  '/pujas/mainpuja':'/pujas',
  '/mainlocation':'/countries',
  '/temples/govind-dev-ji-temple-jaipur':'/pujas',
  '/locations/navagraha-shanti-puja-in-rishikesh-uttarakhand':'/countries/india-cities',
  '/locations/navagraha-shanti-puja-in-mathura-uttar-pradesh':'/countries/india-cities',
  '/city/florida':'/countries/united-states-cities/florida',
  'pujas/sss':'/pujas',
  '/pujas/suroman':'/countries/oman-cities/sur'
  
};

const normalizedLegacyRedirects = new Map<string, string>();
for (const [source, target] of Object.entries(legacyRedirects)) {
  const normKey = source.trim().toLowerCase().replace(/\/+$/, '');
  if (normKey) {
    normalizedLegacyRedirects.set(normKey, target);
  }
}

export function getLegacyRedirect(pathname: string): string | undefined {
  const normPath = pathname.trim().toLowerCase().replace(/\/+$/, '') || '/';
  return normalizedLegacyRedirects.get(normPath);
}
